# Generated by Django 5.0.6 on 2024-09-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_userprofile_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='code',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
