# Generated by Django 5.0.6 on 2024-09-23 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_userprofile_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='code',
        ),
    ]
