# Generated by Django 5.0.6 on 2024-09-23 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_userprofile_code_userprofile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
    ]
