# Generated by Django 5.0.6 on 2024-09-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_userprofile1_userprofile_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='code',
        ),
        migrations.AddField(
            model_name='userprofile1',
            name='code',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
