# Generated by Django 5.0.6 on 2024-09-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_userprofile_code_userprofile1_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile1',
            name='avatar',
            field=models.ImageField(default='photo/sbcf-default-avatar.webp', null=True, upload_to='photo'),
        ),
    ]
